version: '3.8'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks: 
      - foodnetwork
  api:
    image: weegedocker/foodscrapperapi
    container_name: foodscrapper_api
    restart: always
    environment:
      MongoDbConnectionString: mongodb://root:rootpassword@db:27017
      MongoDbDataBaseName: foodscrapper
      IsMySqlDataBase: false    
    ports:
      - "44319:80"
    depends_on:
      - db
    networks: 
      - foodnetwork
networks:
  foodnetwork:
    name: foodnetwork
    driver: bridge